### numpy
numpy定义了python进行矩阵数值计算的基础
> np.add(A,B)

> np.subtract(A,B)

> np.dot(C,D)

> np.matmul(C,D)           ## C@D

> np.multiply(C,D)         ## C*D

In [1]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B = ', np.add(A,B))
print('A-B = ', np.subtract(A,B))

A+B =  [5 5 3]
A-B =  [-3 -1  3]


In [24]:
C = np.array([[1,2,3],
              [1,1,1]])
D = np.array([[4,3,9,9],
              [1,1,2,2],
              [4,2,1,1]])
# 矩阵乘法
print('np.dot(C,D) = \n',np.dot(C,D))
print('np.matmul(C,D) = \n',np.matmul(C,D))
print('        C@D    = \n',np.matmul(C,D))

np.dot(C,D) = 
 [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D) = 
 [[18 11 16 16]
 [ 9  6 12 12]]
        C@D    = 
 [[18 11 16 16]
 [ 9  6 12 12]]


In [25]:
# 元素与元素相乘
D = np.array([[4,3,9,9],
              [1,1,2,2],
              [4,2,1,1]])
print('np.multiply(D,D)= \n',np.multiply(D,D))
print('          D*D   = \n', D*D)

np.multiply(D,D)= 
 [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]
          D*D   = 
 [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]


### np.dot 和 np.matmul的区别

* 都是矩阵乘法
* np.matmul中，禁止矩阵与标量的乘法
* np.matmul中，在矢量乘矢量的内积运算中，matmul与dot没有差别
* np.matmul中，多维的矩阵，将前n-2维视为后2维的元素后，进行乘法操作

#### 矢量内积无区别，结果是标量

In [4]:
t1 = np.array([1,2,3])
t2 = np.array([1,2,3])
print(np.dot(t1,t2))
print(np.matmul(t1,t2))
print(t1*t2) # 元素1 1 乘积

14
14
[1 4 9]


#### 1维与2维矩阵的乘法

In [9]:
a = np.array([1,2,3])
b = np.array([[1,1,1],
              [2,2,2],
              [3,3,3]])
print("np.dot(a,b): ", np.dot(a,b))
print("np.matmul(a,b): ", np.matmul(a,b))
#注意
a*b # 扩展维度后，元素乘积
print("a*b: \n", a*b) 

np.dot(a,b):  [14 14 14]
np.matmul(a,b):  [14 14 14]
a*b: 
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


#### 多维矩阵乘积的比较

In [11]:
m_4_4 = np.array([
                       [1,2,3,4],
                       [3,2,1,4],
                       [5,4,6,7],
                       [11,12,13,14]
                      ])


m_3_4_2 = np.array([
                             [[2,3],
                              [11,9],
                              [32,21],
                              [28,17]],
    
                             [[2,3],
                              [1,9],
                              [3,21],
                              [28,7]],
    
                             [[2,3],
                              [1,9],
                              [3,21],
                              [28,7]]
                            ])

In [12]:
print(m_4_4.shape)
print(m_3_4_2.shape)

(4, 4)
(3, 4, 2)


In [26]:
print('4x4 * 3x4x2 dot:\n {}\n'.format(np.dot(m_4_4,m_3_4_2)))
print('4x4 * 3x4x2 matmul:\n {}\n'.format(np.matmul(m_4_4,m_3_4_2)))

4x4 * 3x4x2 dot:
 [[[232 152]
  [125 112]
  [125 112]]

 [[172 116]
  [123  76]
  [123  76]]

 [[442 296]
  [228 226]
  [228 226]]

 [[962 652]
  [465 512]
  [465 512]]]

4x4 * 3x4x2 matmul:
 [[[232 152]
  [172 116]
  [442 296]
  [962 652]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]]



In [27]:
print('4 4 矩阵 与 3 4 2 矩阵的乘积结果')
print('dot 结果的维度    =',np.dot(m_4_4,m_3_4_2).shape)
print('matmul 结果的维度 =',np.matmul(m_4_4,m_3_4_2).shape)

4 4 矩阵 与 3 4 2 矩阵的乘积结果
dot 结果的维度    = (4, 3, 2)
matmul 结果的维度 = (3, 4, 2)


**检验以下m_4_4与m_3_4_2最后两维的矩阵乘积结果**

In [15]:
np.dot(m_4_4,m_3_4_2[0,:,:])

array([[232, 152],
       [172, 116],
       [442, 296],
       [962, 652]])

In [16]:
np.matmul(m_4_4,m_3_4_2[:,:,0].T)

array([[232, 125, 125],
       [172, 123, 123],
       [442, 228, 228],
       [962, 465, 465]])

#### np.dot 定义：

> dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
